### ISSUE TITLE
Relatório da Iteração 1

### ISSUE THREAD

**Issue by HenryKrz** [garoque/crud-eng-software#7]

**Comment by FabioKopacz** [comment]
### Relatório Iteração 1
Relatório das atividades feitas durante a iteração 1, o que funcionou ou deu errado durante a iteração 
**Período da iteração xx/xx **

_Atividades planejadas_
- Moockups & storyboards.
- Criação das primeiras historias de usuários.

**Atividades realizadas**
- [ ] Moockups & storyboards.
- [ ] Criação das primeiras historias de usuários.

**Atividades não realizadas**
- [ ] Moockups & storyboards.
- [ ] Criação das primeiras historias de usuários.

_Motivações e problemas_
- xxx
- xxx
- xxx
